### ISSUE TITLE
Umbrella issue from cookic

### ISSUE THREAD

**Issue by andfanilo** [andfanilo/pandas_profiling_webservice#1]
Tasks from Cookiecutter's [project README](https://github.com/audreyr/cookiecutter-pypackage/tree/fef9d2260e607ede74cb0150a648346e2b54e9a5) 

- [ ] Create a repo and put it there.
- [ ] Add the repo to your Travis-CI account.
- [ ] Install the dev requirements into a virtualenv. (pip install -r requirements_dev.txt)
- [ ] Run the script travis_pypi_setup.py to encrypt your PyPI password in Travis config and activate automated deployment on PyPI when you push a new tag to master branch.
- [ ] Add the repo to your ReadTheDocs account + turn on the ReadTheDocs service hook.
- [ ] Release your package by pushing a new tag to master.
- [ ] Add a requirements.txt file that specifies the packages you will need for your project and their versions. For more info see the pip docs for requirements files.
- [ ] Activate your project on pyup.io.
